# Generated by Django 4.0.4 on 2023-10-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_avisutilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisutilisateur',
            name='etoiles',
        ),
    ]
