# Generated by Django 4.0.4 on 2023-10-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devis',
            new_name='Devi',
        ),
    ]
